# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app_swift_ui_test_integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  post_install do |installer|
    flutter_post_install(installer)
  end

  # Pods for app_swift_ui_test_integration
  flutter_application_path = '../my_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

end
